version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "4306:3306"  # ✅ Đổi sang port 4306 để tránh xung đột với TablePlus (3307)
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=QuanLyLopHocTrucTuyen
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=my_secret_key
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=QuanLyLopHocTrucTuyen
    depends_on:
      - db
    working_dir: /app
    # Sử dụng wait-for-it + binary app đã build
    command: ["./wait-for-it.sh", "db:3306", "--timeout=30", "--", "./app"]

volumes:
  mysql_data:
